var quiz = [
  {
    q: `Which activity would the registered nurse (RN) delegate to an unlicensed assistive personnel (UAP)?`,
    q2: ``,
    q3: [],
    quesHeading: `<span class="h1hd">3 Management/Leadership: </span>`,
    option: [
      `Assist a client to ambulate who was just admitted with stroke symptoms.`,
      `Encourage additional oral fluids for an elderly client with pneumonia who has developed a fever.`,
      `Report the ability of a client with myasthenia gravis to manage the supper tray independently.`,
      `Record the number of liquid stools of a client who received lactulose for an elevated NH3 level.`,
    ],
    optionFeedback: [
      `This requires assessment of the client’s ability to ambulate safely, which is beyond the scope of practice of a UAP.`,
      `These directions are not sufficiently clear and detailed for the UAP to perform the task.`,
      `This requires assessment of the client’s clinical status, which is beyond the scope of the UAP.`,
      `This task encompasses basic care, elimination, and intake and output; it does not require judgment or the expertise of the RN and can be performed by the UAP.`,
    ],
    optionStyleType: `st-decimal`,
    answer: [3],
    ansText: `<strong>Rationale:</strong> This task encompasses basic care, elimination, and intake and output; it does not require judgment or the expertise of the RN and can be performed by the UAP.`,
    state: `notAnswered`,
    userAnswered: [],
    type: `MCSS`,
  },
  {
    q: `The RN is assigning tasks to the UAP. Which client situation requires the RN to intervene?`,
    q2: ``,
    q3: [],
    quesHeading: `<span class="h1hd">3 Management/Leadership: </span>`,
    option: [
      `Active tuberculosis who is leaving the room without a mask.`,
      `End-stage renal disease requesting orange juice to drink.`,
      `Anemia who is complaining of fatigue and asking for help getting dressed to go home.`,
      `Chronic obstructive pulmonary disorder who removes his oxygen and is leaving the unit to smoke.`,
    ],
    optionFeedback: [
      `A UAP can be delegated to provide a box of masks or to direct the client back to the room.`,
      `A UAP can be directed to provide specific types and amounts of fluids, but orange juice is high in potassium, which is contraindicated for clients in end-stage renal disease.`,
      `A UAP can assist a client to get dressed. Fatigue is an expected finding with anemia.`,
      `A UAP can ask the client to not leave the unit to smoke.`,
    ],
    optionStyleType: `st-decimal`,
    answer: [1],
    ansText: `<strong>Rationale:</strong> A UAP can be directed to provide specific types and amounts of fluids, but orange juice is high in potassium, which is contraindicated for clients in end-stage renal disease.`,
    state: `notAnswered`,
    userAnswered: [],
    type: `MCSS`,
  },
  {
    q: `When entering a client’s room, the RN finds the client threatening to cut herself. Which is the priority intervention?`,
    q2: ``,
    q3: [],
    quesHeading: `<span class="h1hd">3 Management/Leadership: </span>`,
    option: [
      `Call in an extra RN or UAP for the next shift.`,
      `Assign one of the current UAPs to sit with the client.`,
      `Move the client to another room with a roommate.`,
      `Administer an as-needed (PRN) dose of lorazepam.`,
    ],
    optionFeedback: [
      `The charge nurse should plan ahead for staffing, but the immediate focus should be the client’s safety now.`,
      `Because the client is at risk for self-harm, the charge nurse should assign a staff member to stay with the client.`,
      `This will not ensure the client’s safety; also, a staff member, not another client, must always be present with the client.`,
      `Although the client may be anxious, this is not a priority intervention that would ensure her safety.`,
    ],
    optionStyleType: `st-decimal`,
    answer: [1],
    ansText: `<strong>Rationale:</strong> Because the client is at risk for self-harm, the charge nurse should assign a staff member to stay with the client.`,
    state: `notAnswered`,
    userAnswered: [],
    type: `MCSS`,
  },
  {
    q: `A UAP is assisting with the care of several clients on a postpartum unit. Which assignment would the RN delegate to the UAP?`,
    q2: ``,
    q3: [],
    quesHeading: `<span class="h1hd">3 Management/Leadership: </span>`,
    option: [
      `Check fundal firmness and lochia for the clients who delivered vaginally.`,
      `Take vital signs every 15 minutes for a client with preeclampsia.`,
      `Provide breastfeeding instructions for a primigravida.`,
      `Assist with daily care activities for all clients as needed.`,
    ],
    optionFeedback: [
      `Assessment is a responsibility of the RN.`,
      `This is a high-risk client who needs to be evaluated by an RN.`,
      `Teaching is the responsibility of the RN.`,
      `This is the most appropriate assignment for the UAP. The RN should delegate daily care activities to the UAP based on the RN’s assessments of each client’s needs.`,
    ],
    optionStyleType: `st-decimal`,
    answer: [3],
    ansText: `<strong>Rationale:</strong> This is the most appropriate assignment for the UAP. The RN should delegate daily care activities to the UAP based on the RN’s assessments of each client’s needs.`,
    state: `notAnswered`,
    userAnswered: [],
    type: `MCSS`,
  },
  {
    q: `Which client is at the highest risk for respiratory complications?`,
    q2: ``,
    q3: [],
    quesHeading: `<span class="h1hd">4 Advanced Clinical Concepts: </span>`,
    option: [
      `A 21-year-old client with dehydration and cerebral palsy who is dependent in daily activities.`,
      `A 60-year-old client who has had type 2 diabetes for 20 years and was admitted with cellulitis.`,
      `An obese 30-year-old client with hypertension who is noncompliant with the medication regimen.`,
      `A 40-year-old client who takes a loop diuretic, has a serum K<sup>+</sup> of 3.5 mEq/L (3.5 mmol/L) (Ref. range: 3.5–5 mEq/L or mmol/L), and complains of fatigue.`,
    ],
    optionFeedback: [
      `A client with dehydration and cerebral palsy, characterized by uncoordinated, spastic muscle movements, is at increased risk for respiratory problems because of impaired mobility and impaired swallowing.`,
      `This older client is more at risk for renal, cardiac, and vascular complications.`,
      `An obese adult who is noncompliant with antihypertensive medications is more at risk for cardiac or cerebral events than for respiratory problems.`,
      `This middle-aged adult is hypokalemic and fatigued but is not at high risk for respiratory problems.`,
    ],
    optionStyleType: `st-decimal`,
    answer: [0],
    ansText: `<strong>Rationale:</strong> A client with dehydration and cerebral palsy, characterized by uncoordinated, spastic muscle movements, is at increased risk for respiratory problems because of impaired mobility and impaired swallowing.`,
    state: `notAnswered`,
    userAnswered: [],
    type: `MCSS`,
  },
  {
    q: `An RN working at a clinic finds a client in one of the examination rooms slumped over and apneic. The RN notes an empty syringe and needle still in the client’s arm. Which action has the highest priority?`,
    q2: ``,
    q3: [],
    quesHeading: `<span class="h1hd">4 Advanced Clinical Concepts: </span>`,
    option: [
      `Call 911.`,
      `Remove the syringe and needle.`,
      `Assess for a pulse.`,
      `Obtain the automated external defibrillator (AED).`,
    ],
    optionFeedback: [
      `Calling for assistance is a high priority but not the highest.`,
      `The syringe and needle should be removed and possibly sent to a laboratory for analysis of the contents, but this is not a priority.`,
      `Assessing for a pulse is the highest priority to determine whether cardiopulmonary resuscitation (CPR) needs to be initiated.`,
      `This action is needed only if there is no pulse detected.`,
    ],
    optionStyleType: `st-decimal`,
    answer: [2],
    ansText: `<strong>Rationale:</strong> Assessing for a pulse is the highest priority to determine whether cardiopulmonary resuscitation (CPR) needs to be initiated.`,
    state: `notAnswered`,
    userAnswered: [],
    type: `MCSS`,
  },
  {
    q: `A client who is immediately postoperative for abdominal aortic aneurysm repair has been receiving normal saline intravenously at 125 mL/hr. The RN observes dark yellow urine. The hourly output for the past 3 hours was 30 mL, 18 mL, and 10 mL. Which action would the RN take?`,
    q2: ``,
    q3: [],
    quesHeading: `<span class="h1hd">4 Advanced Clinical Concepts: </span>`,
    option: [
      `Administer a bolus D5 ½ normal saline at 200 mL/hr.`,
      `Contact the health care provider (HCP).`,
      `Monitor output for another 2 hours.`,
      `Draw blood samples for blood urea nitrogen (BUN) and creatinine levels.`,
    ],
    optionFeedback: [
      `The decreasing urine output may be a sign of acute renal failure, a complication of aortic aneurysm repair. Giving more fluids may cause the client’s condition to deteriorate.`,
      `Acute renal failure can result from interruption of blood flow during an aortic aneurysm repair. Low urinary output may indicate acute renal failure and requires more immediate intervention from the HCP.`,
      `Urine output has been monitored, and further intervention is needed.`,
      `The BUN and creatinine should be evaluated, but these tests are not the immediate priority.`,
    ],
    optionStyleType: `st-decimal`,
    answer: [1],
    ansText: `<strong>Rationale:</strong> Acute renal failure can result from interruption of blood flow during an aortic aneurysm repair. Low urinary output may indicate acute renal failure and requires more immediate intervention from the HCP.`,
    state: `notAnswered`,
    userAnswered: [],
    type: `MCSS`,
  },
  {
    q: `The RN is evaluating the effects of the administration of fresh frozen plasma (FFP) on a male client diagnosed with cirrhosis. Which finding(s) would indicate a positive outcome?`,
    q2: ``,
    q3: [],
    quesHeading: `<span class="h1hd">4 Advanced Clinical Concepts: </span>`,
    option: [
      `BUN 3.9 mg/dL (3.9 mmol/L) (Ref. range: 10–20 mg/dL or 3.6–7.1 mmol/L); Creatinine 0.7 mg/dL (88 micromol) (Ref. range: 0.6–1.2 mg/dL or 53–106 μmol).`,
      `Hemoglobin level of 10 gm/dL (6.2 mmol/L) (Ref. range: 14–18 gm/dL or 8.7–11.2 mmol/L).`,
      `Return of temperature to normal.`,
      `Decreased bleeding from the gums.`,
      `Negative guaiac for occult bleeding.`,
    ],
    //optionFeedback: [``],
    optionStyleType: `st-decimal`,
    answer: [3, 4],
    ansText: `<strong>Rationale:</strong> <p><strong>BUN 3.9 mg/dL (3.9 mmol/L) (Ref. range: 10–20 mg/dL or 3.6–7.1 mmol/L); Creatinine 0.7 mg/dL (88 micromol) (Ref. range: 0.6–1.2 mg/dL or 53–106 μmol).</strong> These values are not affected by administration of FFP. They assess renal function.</p>
<p><strong>Hemoglobin level of 10 gm/dL (6.2 mmol/L) (Ref. range: 14–18 gm/dL or 8.7–11.2 mmol/L).</strong> FFP does not affect hemoglobin levels.</p>
<p><strong>Return of temperature to normal.</strong> Although monitoring the client’s temperature is important, FFP does not have a direct effect on this parameter.</p>
<p><strong>Decreased bleeding from the gums.</strong> FFP replaces clotting factors; therefore, a decrease in bleeding is an expected, positive outcome.</p>
<p><strong>Negative guaiac for occult bleeding.</strong> FFP replaces clotting factors; therefore, no occult (hidden) bleeding would be an expected, positive outcome.</p>`,
    state: `notAnswered`,
    userAnswered: [],
    type: `MCMS`,
  },
  {
    q: `A client’s arterial blood gas (ABG) results are as follows: pH 7.29 (Ref. range: 7.35–7.45), PCO<sub>2</sub> 55 mm Hg (Ref. range: 35–45), and HCO<sub>3</sub> 26 mEq/L (Ref. range: 21–28 mEq/L). Which compensatory response would the RN expect to see?`,
    q2: ``,
    q3: [],
    quesHeading: `<span class="h1hd">4 Advanced Clinical Concepts: </span>`,
    option: [
      `Respiratory rate of 30 breaths/min.`,
      `Apical rate of 120 beats/minute.`,
      `Potassium level of 5.8 mEq/L (5.8 mmol/L) (Ref. range: 3.5–5 mEq/L or 3.5–5 mmol/L).`,
      `Complaints of pounding headache.`,
    ],
    optionFeedback: [
      `The client is experiencing respiratory acidosis. In addition to the metabolic system compensating, the respiratory system may also compensate.`,
      `Acid-base imbalances are compensated primarily by the lungs and the renal system. Plasma proteins and ionic shifts (intracellular) also serve as buffering systems. Tachycardia does not serve as a compensatory mechanism.`,
      `To compensate for the acidosis created by increased CO2, K+ ions are released from cellular proteins and H+ ions take their place, bound to the proteins. The result is frequently serum hyperkalemia.`,
      `Headache may be a manifestation of CO2 retention, but it is not a compensatory mechanism for respiratory acidosis.`,
    ],
    optionStyleType: `st-decimal`,
    answer: [0],
    ansText: `<strong>Rationale:</strong> The client is experiencing respiratory acidosis. In addition to the metabolic system compensating, the respiratory system may also compensate.`,
    state: `notAnswered`,
    userAnswered: [],
    type: `MCSS`,
  },
  {
    q: `A client with chronic back pain is not receiving adequate pain relief from oral analgesics. Which alternative action would the RN explore to promote the client’s independence?`,
    q2: ``,
    q3: [],
    quesHeading: `<span class="h1hd">4 Advanced Clinical Concepts: </span>`,
    option: [
      `Ask the HCP to increase the analgesic dosage.`,
      `Obtain a prescription for a second analgesic to be given by the IV route.`,
      `Consider the client’s receptivity to complementary therapy.`,
      `Encourage counseling to prevent future addiction.`,
    ],
    optionFeedback: [
      `Although this intervention may improve pain relief, it may not promote self-care without increasing side effects that could affect the client’s independence.`,
      `The IV route does not promote self-care and may cause additional side effects that interfere with the client’s ability to carry out activities of daily living independently.`,
      `This action supports self-care without the high level of adverse effects associated with additional medication. It is the least invasive measure, and it promotes the active participation (self-care) of the client.`,
      `Referrals may be needed, but the RN should teach clients about potential problems with medications and measures to manage pain and maintain self-care.`,
    ],
    optionStyleType: `st-decimal`,
    answer: [2],
    ansText: `<strong>Rationale:</strong> This action supports self-care without the high level of adverse effects associated with additional medication. It is the least invasive measure, and it promotes the active participation (self-care) of the client.`,
    state: `notAnswered`,
    userAnswered: [],
    type: `MCSS`,
  },
  {
    q: `A client at 41 weeks’ gestation who is in active labor calls the RN to report that her membranes have ruptured. The RN performs a vaginal examination and discovers that the umbilical cord has prolapsed. Which intervention would the RN implement first?`,
    q2: ``,
    q3: [],
    quesHeading: `<span class="h1hd">5 Maternal/Newborn Nursing: </span>`,
    option: [
      `Move the presenting fetal part off the cord.`,
      `Cover the cord with sterile moist saline gauze.`,
      `Prepare for an emergency cesarean delivery.`,
      `Administer O2 by face mask at 10 L/min.`,
    ],
    optionFeedback: [
      `This action is the most critical intervention. The RN must prevent compression of the cord by the presenting part because that would impair fetal circulation, leading to morbidity and, possibly, death.`,
      `If the cord is protruding outside the vagina, this action should be taken to prevent drying of the Wharton’s jelly. However, another RN should do this while the first RN maintains elevation of the presenting part off the cord.`,
      `This is implemented by the staff while the RN keeps the presenting part elevated off the cord.`,
      `Oxygen should be provided to the mother to increase oxygen delivery to the fetus via the placenta; however, another RN should do this while first the RN keeps the presenting part elevated off the cord.`,
    ],
    optionStyleType: `st-decimal`,
    answer: [0],
    ansText: `<strong>Rationale:</strong> This action is the most critical intervention. The RN must prevent compression of the cord by the presenting part because that would impair fetal circulation, leading to morbidity and, possibly, death.`,
    state: `notAnswered`,
    userAnswered: [],
    type: `MCSS`,
  },
  {
    q: `A client at 39 weeks’ gestation plans to have an epidural block when labor is established. Which intervention(s) would the RN implement to prevent side effects?`,
    q2: ``,
    q3: [],
    quesHeading: `<span class="h1hd">5 Maternal/Newborn Nursing: </span>`,
    option: [
      `Teach about the procedure and effects of the epidural.`,
      `Place the client in a chair next to the bed.`,
      `Administer a bolus of 500 mL of normal saline solution.`,
      `Monitor the fetal heart rate and contractions continuously.`,
      `Assist the client to empty her bladder every 2 hours.`,
    ],
    //optionFeedback: [``],],
    optionStyleType: `st-decimal`,
    answer: [2, 4],
    ansText: `<strong>Rationale:</strong> <p><strong>Teach the client about the procedure and the effects of the epidural.</strong> Teaching is an important nursing intervention to alleviate anxiety, but it does not prevent any of the possible side effects.</p>
<p><strong>Place the client in a chair next to the bed.</strong> Epidural block reduces lower extremity sensation and movement to varying degrees. Any upright positions such as walking and standing may not be possible during epidural pain management and may not prevent side effects.</p>
<p><strong>Administer a bolus of 500 mL of normal saline solution.</strong> Prehydration increases maternal blood volume and prevents hypotension, which occurs as a result of vasodilation, a side effect of epidural anesthesia. A saline solution is used to prevent fetal secretion of insulin that later places the neonate at risk for hypoglycemia.</p>
<p><strong>Monitor the fetal heart rate and contractions continuously.</strong> Vital signs should be monitored every 5 minutes immediately after the initial epidural dose, and if the client’s condition is stable, then every 15 minutes. Continuous fetal heart rate and contraction monitors should be applied during this time also. However, this does not prevent side effects.</p>
<p><strong>Assist the client to empty her bladder every 2 hours.</strong> Assisting the client to void every 2 hours prevents bladder distention.</p>`,
    state: `notAnswered`,
    userAnswered: [],
    type: `MCMS`,
  },
  {
    q: `A female client presents in the emergency department with right lower quadrant abdominal pain and pain in her right shoulder. She has no vaginal bleeding, and her last menses was 6 weeks ago. Which action would the RN take first?`,
    q2: ``,
    q3: [],
    quesHeading: `<span class="h1hd">5 Maternal/Newborn Nursing: </span>`,
    option: [
      `Assess for abdominal rebound pain, distention, and fever.`,
      `Obtain a complete set of vital signs and establish IV access.`,
      `Observe for recent musculoskeletal injury, bruising, or abuse.`,
      `Collect specimens for pregnancy test, hemoglobin, and white blood cell count.`,
    ],
    optionFeedback: [
      `Bleeding related to an ectopic pregnancy (based on the client’s history) may present these manifestations, but the RN should first assess the client for early signs of hypovolemic shock.`,
      `The RN should first evaluate the client for vital sign changes related to blood loss due to a possible ruptured ectopic pregnancy (an obstetrical emergency). Vascular access is vital in an emergency situation.`,
      `This may be part of the assessment if a life-threatening situation is ruled out first.`,
      `Specimens for a pregnancy test and complete blood count should be collected. However, the RN should first notify the HCP of the client’s status, based on the presenting vital signs and symptoms.`,
    ],
    optionStyleType: `st-decimal`,
    answer: [1],
    ansText: `<strong>Rationale:</strong> The RN should first evaluate the client for vital sign changes related to blood loss due to a possible ruptured ectopic pregnancy (an obstetrical emergency). Vascular access is vital in an emergency situation.`,
    state: `notAnswered`,
    userAnswered: [],
    type: `MCSS`,
  },
  {
    q: `An RN has been assigned a pregnant client who has heart disease. The client’s condition has been diagnosed as New York Heart Association (NYHA) class II cardiac disease. Which important fact(s) about activities of daily living while pregnant would the RN teach this client?`,
    q2: ``,
    q3: [],
    quesHeading: `<span class="h1hd">5 Maternal/Newborn Nursing: </span>`,
    option: [
      `Increase fiber in the diet.`,
      `Anticipate the need for rest breaks after activity.`,
      `Notify the HCP if her rings do not fit.`,
      `Maintain bed rest with bathroom privileges.`,
      `Start a low-impact aerobic exercise program.`,
    ],
    //optionFeedback: [``],],
    optionStyleType: `st-decimal`,
    answer: [0, 1, 2],
    ansText: `<strong>Rationale:</strong> <p><strong>Increase fiber in the diet.</strong> Restrictions in activities of daily living for clients with NYHA Class II cardiac disease create a risk factor for constipation.</p>
<p><strong>Anticipate the need for rest breaks after activity.</strong> Individuals with NYHA Class II cardiac disease may have limitations on activity and need periods of rest throughout the day, but especially after periods of activity.</p>
<p><strong>Notify the HCP if her rings do not fit.</strong> Tight rings may indicate weight gain, and the client is at risk for congestive heart failure.</p>
<p><strong>Maintain bed rest with bathroom privileges.</strong> It is not necessary to maintain bed rest for a client with NYHA Class II cardiac disease.</p>
<p><strong>Start a low-impact aerobic exercise program.</strong> Individuals with NYHA class II cardiac disease may have some slight limitation of activity. Additionally, during pregnancy is not an ideal time to start a new exercise program.</p>`,
    state: `notAnswered`,
    userAnswered: [],
    type: `MCMS`,
  },
  {
    q: `A client with type II diabetes is scheduled for an intravenous pyelogram (IVP). Which assessment is most important for the RN to complete before the test is performed?`,
    q2: ``,
    q3: [],
    quesHeading: `<span class="h1hd">6 Medical-Surgical: </span>`,
    option: [
      `Baseline vital signs.`,
      `Current medication list.`,
      `Coagulation status.`,
      `Electrolyte levels.`,
    ],
    optionFeedback: [
      `Baseline values are important but there is a higher priority.`,
      `This is a priority. If the client is taking an oral diabetic agent with metformin, the RN may need to hold the medication for 48 hours before the IVP because of potentially decreased kidney function.`,
      `There is no risk of bleeding related to an IVP.`,
      `Electrolyte levels are not affected by an IVP, and high or low levels are not considered a contraindication for completing the test.`,
    ],
    optionStyleType: `st-decimal`,
    answer: [1],
    ansText: `<strong>Rationale:</strong> This is a priority. If the client is taking an oral diabetic agent with metformin, the RN may need to hold the medication for 48 hours before the IVP because of potentially decreased kidney function.`,
    state: `notAnswered`,
    userAnswered: [],
    type: `MCSS`,
  },
  {
    q: `The RN is teaching a client who has chronic urinary tract infections about a prescription for ciprofloxacin 500 mg PO bid (twice daily). Which side effect(s) could the client expect while taking this medication?`,
    q2: ``,
    q3: [],
    quesHeading: `<span class="h1hd">6 Medical-Surgical: </span>`,
    option: [
      `Photosensitivity.`,
      `Dyspepsia.`,
      `Diarrhea.`,
      `Urinary frequency.`,
      `Anemia.`,
    ],
    //optionFeedback: [``],],
    optionStyleType: `st-decimal`,
    answer: [0, 1],
    ansText: `<strong>Rationale:</strong> <p><strong>Photosensitivity.</strong> This is a side effect of ciprofloxacin; exposure to sunlight or tanning beds should be avoided. The client should be instructed to use sunscreen and protective clothing.</p>
<p><strong>Dyspepsia.</strong> Ciprofloxacin causes gastrointestinal (GI) irritation, nausea and vomiting, and abdominal pain, which should be reported.</p>
<p><strong>Diarrhea.</strong> Watery, foul-smelling diarrhea is an adverse reaction to ciprofloxacin that indicates pseudomembranous colitis; this should be reported and requires immediate intervention. This is not an expected side effect.</p>
<p><strong>Urinary frequency.</strong> Urinary frequency may indicate that the medication is ineffective and should be reported, but it is not an expected side effect.</p>
<p><strong>Anemia.</strong> This is not a side effect of ciprofloxacin.</p>`,
    state: `notAnswered`,
    userAnswered: [],
    type: `MCMS`,
  },
  {
    q: `An RN working on a hospice unit finds a client crying. The client states that he is afraid to die. Which action(s) would the RN implement?`,
    q2: ``,
    q3: [],
    quesHeading: `<span class="h1hd">6 Medical-Surgical: </span>`,
    option: [
      `Sit quietly with the client and listen to his concerns.`,
      `Provide the client with privacy.`,
      `Give the client an antianxiety medication.`,
      `Contact the client’s spiritual counselor or pastor.`,
      `Assess the client for signs of impending death.`,
    ],
    //optionFeedback: [``],],
    optionStyleType: `st-decimal`,
    answer: [0, 3],
    ansText: `<strong>Rationale:</strong> <p><strong>Sit quietly with the client and listen to his concerns.</strong> Silence, or offering one’s presence, is an effective technique that lets the client share as he desires and also indicates that the RN cares.</p>
<p><strong>Provide the client with privacy.</strong> The client has shared that he is afraid. Further isolating the client from others will not address this need.</p>
<p><strong>Give the client an antianxiety medication.</strong> The RN may eventually decide to give the client a medication to help with his anxiety, but this should not be the first action.</p>
<p><strong>Contact the client’s spiritual counselor or minister.</strong> Facing death is a spiritual issue. Requesting help from the client’s spiritual provider is appropriate.</p>
<p><strong>Assess the client for signs of impending death.</strong> The client is awake and oriented. There is no indication that the client’s death is imminent.</p>`,
    state: `notAnswered`,
    userAnswered: [],
    type: `MCMS`,
  },
  {
    q: `A male client with a peritoneal dialysis (PD) catheter calls the clinic to report that he feels poorly and has a fever. Which is the best response by the RN?`,
    q2: ``,
    q3: [],
    quesHeading: `<span class="h1hd">6 Medical-Surgical: </span>`,
    option: [
      `Encourage him to come to the clinic today for assessment.`,
      `Instruct him to increase his fluid intake to 3 L/day.`,
      `Review his PD regimen.`,
      `Inquire about his recent dietary intake of protein and iron.`,
    ],
    optionFeedback: [
      `PD catheters are used in PD. They are often used at home by the client, placing the client at risk for peritoneal infection. Because dialysis clients usually have some degree of compromised immunity, the client should come to the clinic for assessment.`,
      `Clients who need dialysis retain fluid and usually are restricted to an intake that is only 300 mL greater than output.`,
      `The RN should evaluate the client’s PD regimen, but assessing him for infection is a higher priority.`,
      `Iron deficiency and protein loss are common problems in clients who are receiving PD. Dietary intake is important, but it is not a higher priority than possible infection.`,
    ],
    optionStyleType: `st-decimal`,
    answer: [0],
    ansText: `<strong>Rationale:</strong> PD catheters are used in PD. They are often used at home by the client, placing the client at risk for peritoneal infection. Because dialysis clients usually have some degree of compromised immunity, the client should come to the clinic for assessment.`,
    state: `notAnswered`,
    userAnswered: [],
    type: `MCSS`,
  },
  {
    q: `The RN is reviewing the cardiac markers for a client who was admitted with the diagnosis of chest pain. Which marker is best to determine cardiac damage?`,
    q2: ``,
    q3: [],
    quesHeading: `<span class="h1hd">6 Medical-Surgical: </span>`,
    option: [
      `Troponin levels.`,
      `Myoglobin level.`,
      `Creatine kinase myocardial band (CK-MB) level.`,
      `Lactate dehydrogenase (LDH) level.`,
    ],
    optionFeedback: [
      `A rise in the troponin levels is diagnostic of myocardial injury and is considered the gold standard.`,
      `An increase in myoglobin is indicative of muscle damage but is not specific to cardiac damage.`,
      `This isoenzyme is useful for supporting a diagnosis of myocardial infarction and in determining the extent and time of the infarct.`,
      `The LDH level is not currently used to determine recent cardiac damage.`,
    ],
    optionStyleType: `st-decimal`,
    answer: [0],
    ansText: `<strong>Rationale:</strong> A rise in the troponin levels is diagnostic of myocardial injury and is considered the gold standard.`,
    state: `notAnswered`,
    userAnswered: [],
    type: `MCSS`,
  },
  {
    q: `The RN is providing discharge instructions to a client who has been diagnosed with angina pectoris. Which instruction is most important?`,
    q2: ``,
    q3: [],
    quesHeading: `<span class="h1hd">6 Medical-Surgical: </span>`,
    option: [
      `Avoid activity that involves the Valsalva maneuver.`,
      `Seek emergency treatment if chest pain persists after the third nitroglycerin dose.`,
      `Rest for 30 minutes after having chest pain before resuming activity.`,
      `Keep extra nitroglycerin in an airtight, light-resistant bottle.`,
    ],
    optionFeedback: [
      `Although minimizing or avoiding the Valsalva maneuver decreases anginal pain, this is not the most important factor.`,
      `This instruction is most important because chest pain characteristic of acute myocardial infarction persists longer than 15 minutes, and delaying medical treatment can be life-threatening.`,
      `Waiting 30 minutes may be recommended, but the need to call 911 if chest pain persists is more important.`,
      `This is excellent medication teaching, but it does not have the same urgency as seeking emergency care.`,
    ],
    optionStyleType: `st-decimal`,
    answer: [1],
    ansText: `<strong>Rationale:</strong> This instruction is most important because chest pain characteristic of acute myocardial infarction persists longer than 15 minutes, and delaying medical treatment can be life-threatening.`,
    state: `notAnswered`,
    userAnswered: [],
    type: `MCSS`,
  },
  {
    q: `The RN is providing discharge teaching for a client who has been prescribed diltiazem. Which dietary instruction has the highest priority?`,
    q2: ``,
    q3: [],
    quesHeading: `<span class="h1hd">6 Medical-Surgical: </span>`,
    option: [
      `Maintain a low-sodium diet.`,
      `Eat a banana each morning.`,
      `Ingest high-fiber foods daily.`,
      `Avoid grapefruit products.`,
    ],
    optionFeedback: [
      `The client may need to restrict sodium intake, but it is not specific for diltiazem.`,
      `If the client has low potassium, this should be recommended.`,
      `This is an excellent teaching point for everyone, but it is not specific for diltiazem.`,
      `Grapefruit should be avoided during therapy with calcium channel blockers because it can cause an increase in the serum drug level, predisposing the client to hypotension.`,
    ],
    optionStyleType: `st-decimal`,
    answer: [3],
    ansText: `<strong>Rationale:</strong> Grapefruit should be avoided during therapy with calcium channel blockers because it can cause an increase in the serum drug level, predisposing the client to hypotension.`,
    state: `notAnswered`,
    userAnswered: [],
    type: `MCSS`,
  },
  {
    q: `The RN is teaching a young adult female who has a history of Raynaud disease how to control her pain. Which information would the RN offer?`,
    q2: ``,
    q3: [],
    quesHeading: `<span class="h1hd">6 Medical-Surgical: </span>`,
    option: [
      `Take oral analgesics at regularly spaced intervals.`,
      `Avoid extremes of heat and cold.`,
      `Limit foods and fluids that contain caffeine.`,
      `Keep the affected extremities in a dependent position.`,
    ],
    optionFeedback: [
      `Pain is not always associated with Raynaud disease, as is the feeling of cold hands and fingers and pallor. If pain is sporadic or situational, it should not require regular use of analgesics.`,
      `In Raynaud disease, vascular spasms of the hands and fingers are triggered by exposure to extremes of heat or cold, which causes the characteristic pallor and cold-to-the-touch symptoms of the upper extremities.`,
      `Caffeine is not the primary trigger of the episodes; however, if the client notes that caffeine contributes to the blanching and coldness, it should be avoided.`,
      `This is not effective for a client with Raynaud disease.`,
    ],
    optionStyleType: `st-decimal`,
    answer: [1],
    ansText: `<strong>Rationale:</strong> In Raynaud disease, vascular spasms of the hands and fingers are triggered by exposure to extremes of heat or cold, which causes the characteristic pallor and cold-to-the-touch symptoms of the upper extremities.`,
    state: `notAnswered`,
    userAnswered: [],
    type: `MCSS`,
  },
  {
    q: `The clinic nurse is caring for a client taking argatroban for atrial fibrillation. Which information is essential for the clinic nurse to include in the client’s teaching plan?`,
    q2: ``,
    q3: [],
    quesHeading: `<span class="h1hd">6 Medical-Surgical: </span>`,
    option: [
      `Have protamine sulfate available.`,
      `Notify the HCP of any unusual bleeding.`,
      `Eat a diet high in green leafy vegetables.`,
      `Keep the medication in a dark, dry container.`,
      `Avoid aspirin or aspirin-containing medications.`,
    ],
    //optionFeedback: [``],],
    optionStyleType: `st-decimal`,
    answer: [1, 4],
    ansText: `<strong>Rationale:</strong> <p><strong>Have protamine sulfate available.</strong> Protamine sulfate is the antidote for heparin, not argatroban</p>
<p><strong>Notify the HCP of any unusual bleeding.</strong> GI bleeding or excessive bleeding is an adverse effect. The client needs to notify their HCP immediately.</p>
<p><strong>Eat a diet high in green leafy vegetables.</strong> This is a good recommendation for clients low in vitamin K but is not an issue for clients on argatroban.</p>
<p><strong>Keep the medication in a dark, dry container.</strong> This is essential for nitroglycerin and some other medications but not for argatroban.
</p>
<p><strong>Avoid aspirin or aspirin-containing medications
</strong> Aspirin and argatroban can have an additive effect and result in bleeding.
</p>`,
    state: `notAnswered`,
    userAnswered: [],
    type: `MCMS`,
  },
  {
    q: `A client who was admitted to the hospital with cancer of the larynx is scheduled for a laryngectomy tomorrow. Which is the client’s priority learning need tonight?`,
    q2: ``,
    q3: [],
    quesHeading: `<span class="h1hd">6 Medical-Surgical: </span>`,
    option: [
      `Anticipated body image changes.`,
      `Pain management expectations.`,
      `Communication techniques.`,
      `Postoperative nutritional needs.`,
    ],
    optionFeedback: [
      `This is a concern after surgery, when the immediate life-threatening insult of cancer has been assimilated and basic needs have been met.`,
      `Pain relief expectations are a priority, but the inability to convey (communicate) a subjective symptom, such as pain, is the fear the client perceives first.`,
      `A client who is in crisis and anticipating the immediate postoperative period is concerned with immediate needs, such as the ability to express and convey a subjective symptom (e.g., pain) and obtain the needed intervention.`,
      `Nutrition is important to promote healing, but the ability to communicate subjective needs is a higher priority.`,
    ],
    optionStyleType: `st-decimal`,
    answer: [2],
    ansText: `<strong>Rationale:</strong> A client who is in crisis and anticipating the immediate postoperative period is concerned with immediate needs, such as the ability to express and convey a subjective symptom (e.g., pain) and obtain the needed intervention.`,
    state: `notAnswered`,
    userAnswered: [],
    type: `MCSS`,
  },
  {
    q: `A victim of a motor vehicle collision is dead on arrival at the emergency department. The significant other arrives and is noticeably upset. Which action would the RN take to assist the significant other with this crisis?`,
    q2: ``,
    q3: [],
    quesHeading: `<span class="h1hd">7 Psychiatric Nursing: </span>`,
    option: [
      `Ask whether there are family, friends, or clergy to call.`,
      `Inform the significant other about the treatment the victim received.`,
      `Provide education about the stages of grief and loss.`,
      `Assess the significant other’s level of anxiety.`,
    ],
    optionFeedback: [
      `The RN should help the significant other identify support systems and resources that are helpful in coping with a crisis situation, such as the sudden death of a spouse.`,
      `The significant other may be unable to process information during the crisis, and the RN should focus on immediate needs for coping and support.`,
      `Educating the significant other about grief and loss is not an immediate priority in a crisis and should be provided after they begin to cope with the situation.`,
      `Although the RN should assess the significant other for anxiety, the immediate intervention should include a directive approach to assist the spouse in dealing with the stressful event.`,
    ],
    optionStyleType: `st-decimal`,
    answer: [0],
    ansText: `<strong>Rationale:</strong> The RN should help the significant other identify support systems and resources that are helpful in coping with a crisis situation, such as the sudden death of a spouse.`,
    state: `notAnswered`,
    userAnswered: [],
    type: `MCSS`,
  },
  {
    q: `The RN is planning to lead a seminar for community health RNs on violence against women during pregnancy. Which statement describes an appropriate technique for assessing for violence?`,
    q2: ``,
    q3: [],
    quesHeading: `<span class="h1hd">7 Psychiatric Nursing: </span>`,
    option: [
      `Women should be assessed only if they are part of a high-risk group.`,
      `Women may be assessed in the presence of young children but not intimate partners.`,
      `The assessment only needs to be completed at the beginning of the pregnancy.`,
      `Women should be reassessed face to face by an RN as the pregnancy progresses.`,
    ],
    optionFeedback: [
      `Violence against women occurs in all ethnic groups and at all income levels.`,
      `It is important to assess women without their partners present; it is also important that verbal children not be present because they may repeat what is heard. Infants may be present.`,
      `Many women do not reveal violence the first time they are asked. As trust develops between the RN and the client, the woman may be more comfortable sharing her story. Also, violence may start later in the pregnancy.`,
      `More than one face-to-face interview elicits the highest reports of violence during pregnancy.`,
    ],
    optionStyleType: `st-decimal`,
    answer: [3],
    ansText: `<strong>Rationale:</strong> More than one face-to-face interview elicits the highest reports of violence during pregnancy.`,
    state: `notAnswered`,
    userAnswered: [],
    type: `MCSS`,
  },
  {
    q: `The charge nurse reminds clients on the mental health unit that breakfast is at 8 AM, medications are given at 9 AM, and group therapy sessions begin at 10 AM. Which treatment modality has been implemented?`,
    q2: ``,
    q3: [],
    quesHeading: `<span class="h1hd">7 Psychiatric Nursing: </span>`,
    option: [
      `Milieu therapy.`,
      `Behavior modification.`,
      `Peer therapy.`,
      `Problem-solving.`,
    ],
    optionFeedback: [
      `Milieu therapy uses resources and activities in the environment to assist with improving social functioning and activities of daily living.`,
      `Behavior modification involves changing behaviors using positive and negative reinforcements to allow desired activities or remove privileges.`,
      `Peer therapy is not a single therapeutic modality; it involves the interaction of peers who are responsible for supporting, sharing, and compromising within their peer group and milieu.`,
      `Problem-solving is used in crisis intervention; it focuses on problem identification and ways to return to previous levels of functioning.`,
    ],
    optionStyleType: `st-decimal`,
    answer: [0],
    ansText: `<strong>Rationale:</strong> Milieu therapy uses resources and activities in the environment to assist with improving social functioning and activities of daily living.`,
    state: `notAnswered`,
    userAnswered: [],
    type: `MCSS`,
  },
  {
    q: `The RN is accompanying a male client to the radiography department when he becomes panic stricken at the elevator and states, “I can’t get on that elevator.” Which action would the RN take first?`,
    q2: ``,
    q3: [],
    quesHeading: `<span class="h1hd">7 Psychiatric Nursing: </span>`,
    option: [
      `Ask one more staff member to ride in the elevator.`,
      `Offer a prescribed anti-anxiety medication.`,
      `Begin desensitization about riding the elevator.`,
      `Affirm the client’s fears about riding the elevator.`,
    ],
    optionFeedback: [
      `One more staff member will not be able to mobilize the client to ride the elevator. The client must first recognize his feelings about the phobia and accept the need to change his behavior. Additional individuals in the elevator may actually increase the client’s anxiety.`,
      `Offering an antianxiety medication may be needed to proceed with desensitization, but it not the first action.`,
      `Desensitizing the client may be implemented, but first the client should identify his fears and recognize his anxiety.`,
      `The RN should first validate and allow the client to affirm his anxiety and fears about riding the elevator. Then options to initiate desensitization may be considered.`,
    ],
    optionStyleType: `st-decimal`,
    answer: [3],
    ansText: `<strong>Rationale:</strong> The RN should first validate and allow the client to affirm his anxiety and fears about riding the elevator. Then options to initiate desensitization may be considered.`,
    state: `notAnswered`,
    userAnswered: [],
    type: `MCSS`,
  },
  {
    q: `A male client suffering from posttraumatic stress disorder (PTSD) is found one night trying to strangle his roommate. Which intervention is the RN’s highest priority?`,
    q2: ``,
    q3: [],
    quesHeading: `<span class="h1hd">7 Psychiatric Nursing: </span>`,
    option: [
      `Give the client a sedative or hypnotic.`,
      `Administer an antipsychotic.`,
      `Assign a UAP to sit with the client.`,
      `Process with both clients about event.`,
    ],
    optionFeedback: [
      `While this may help the client with anxiety, safety is the priority.`,
      `An antipsychotic medication is indicated if the client is psychotic and agitated; however, the RN should ensure the safety of both clients first.`,
      `The RN should implement safety precautions immediately and place a sitter with the client.`,
      `Although both clients should talk about the incident, this is not an opportune time, and the clients should be separated to provide a safe environment.`,
    ],
    optionStyleType: `st-decimal`,
    answer: [2],
    ansText: `<strong>Rationale:</strong> The RN should implement safety precautions immediately and place a sitter with the client.`,
    state: `notAnswered`,
    userAnswered: [],
    type: `MCSS`,
  },
  {
    q: `The RN is updating the plan of care for a client who has a borderline personality disorder. Which intervention is most important to implement?`,
    q2: ``,
    q3: [],
    quesHeading: `<span class="h1hd">7 Psychiatric Nursing: </span>`,
    option: [
      `Assign the same RN to care for the client.`,
      `Avoid challenging inappropriate behavior.`,
      `Limit the client’s contact with other clients.`,
      `Remove consequences for acting-out behaviors.`,
    ],
    optionFeedback: [
      `The best intervention is to provide consistency and avoid splitting the staff by assigning the client to only one RN.`,
      `The RN should assist the client to recognize manipulative behavior and set limits on manipulative behaviors as necessary.`,
      `Socialization should be encouraged to improve the client’s social skills.`,
      `Firm limits with clear expectations and consequences are needed for manipulative clients.`,
    ],
    optionStyleType: `st-decimal`,
    answer: [0],
    ansText: `<strong>Rationale:</strong> The best intervention is to provide consistency and avoid splitting the staff by assigning the client to only one RN.`,
    state: `notAnswered`,
    userAnswered: [],
    type: `MCSS`,
  },
  {
    q: `A female adolescent is admitted to the mental health unit for anorexia nervosa. In planning care, which is the RN’s highest priority?`,
    q2: ``,
    q3: [],
    quesHeading: `<span class="h1hd">7 Psychiatric Nursing: </span>`,
    option: [
      `Teach the client the importance of self-expression.`,
      `Supervise the client’s activities closely.`,
      `Include the client in daily group therapy.`,
      `Facilitate social interactions with others.`,
    ],
    optionFeedback: [
      `Self-expression of feelings is important, but reestablishing normal eating habits and physiological integrity is the priority intervention.`,
      `The RN should monitor and supervise the client’s activities to prevent binging, purging, or avoiding meals.`,
      `The client should be included in daily groups, but the priority is physiological needs and monitoring meals.`,
      `The client should be given opportunities to socialize, but monitoring activities during the day, especially meals, is the priority.`,
    ],
    optionStyleType: `st-decimal`,
    answer: [1],
    ansText: `<strong>Rationale:</strong> The RN should monitor and supervise the client’s activities to prevent binging, purging, or avoiding meals.`,
    state: `notAnswered`,
    userAnswered: [],
    type: `MCSS`,
  },
  {
    q: `The charge RN is planning the daily schedule for clients on the mental health unit. Which activity would be assigned to a male client who is manic?`,
    q2: ``,
    q3: [],
    quesHeading: `<span class="h1hd">7 Psychiatric Nursing: </span>`,
    option: [
      `A basketball game in the gym.`,
      `Jogging at least 1 mile.`,
      `A table tennis game with a peer.`,
      `Group activity with the art therapist.`,
    ],
    optionFeedback: [
      `The client should avoid any potentially competitive physical activity, especially contact sports, that can stimulate aggressive acting out.`,
      `Jogging is the best activity for this client because it is a noncompetitive physical activity, and it requires the use of large muscle groups that expend energy associated with mania.`,
      `The client should not be assigned to any competitive activities that can frustrate him and stimulate mood swings.`,
      `A manic client may become disruptive and distracted in an art group; physical activity using large muscle groups is more effective in expending energy.`,
    ],
    optionStyleType: `st-decimal`,
    answer: [1],
    ansText: `<strong>Rationale:</strong> Jogging is the best activity for this client because it is a noncompetitive physical activity, and it requires the use of large muscle groups that expend energy associated with mania.`,
    state: `notAnswered`,
    userAnswered: [],
    type: `MCSS`,
  },
  {
    q: `An RN is planning the client assignments for the night shift. The nursing team includes an RN, a licensed practical nurse (LPN), and two UAPs. Which duty/duties would be delegated to the UAPs?`,
    q2: ``,
    q3: [],
    quesHeading: `<span class="h1hd">8 Leadership and Delegation: </span>`,
    option: [
      `Transport a client to the radiology department for a computed tomography (CT) scan.`,
      `Bathe a client with sickle cell disease who has multiple IV lines and a client-controlled analgesia pump.`,
      `Turn a 92-year-old client who has end-stage heart failure and a do-not-resuscitate order.`,
      `Report to the HCP the fingerstick blood glucose level of 49 mg/dL (2.7 mmol/L) (Ref. range: 74–106 mg/dL or 4.1–5.9 mmol/L).`,
      `Feed a female client her first meal after she experienced a stroke.`,
    ],
    //optionFeedback: [``],
    optionStyleType: `st-decimal`,
    answer: [0, 1, 2],
    ansText: `<strong>Rationale:</strong> <p><strong>Transport a client to the radiology department for a CT scan.</strong> The UAP can safely transport a stable client.</p>
<p><strong>Bathe a client with sickle cell disease who has multiple IV lines and a client-controlled analgesia pump.</strong> Bathing clients is a hygiene task that can be delegated to the UAP.</p>
<p><strong>Turn a 92-year-old client who has end-stage heart failure and a do-not-resuscitate order.</strong> Turning clients is a duty that can be delegated to the UAP.</p>
<p><strong>Report to the HCP the fingerstick blood glucose level of 49 mg/dL (2.7 mmol/L) (Ref. range: 74–106 or 4.1–5.9).</strong> Discussing the client’s lab results is a duty for the RN.</p>
<p><strong>Feed a female client her first meal after she experienced a stroke.</strong> The RN needs to assess the client’s ability to swallow. The UAP can perform noninvasive and nonsterile activities (options 1, 2, and 3).</p>`,
    state: `notAnswered`,
    userAnswered: [],
    type: `MCMS`,
  },
  {
    q: `A hospitalized client has been newly diagnosed with type 2 diabetes. Which task(s) can the RN delegate to the UAP?`,
    q2: ``,
    q3: [],
    quesHeading: `<span class="h1hd">8 Leadership and Delegation: </span>`,
    option: [
      `Contacting the dietitian for a prescribed consult.`,
      `Reviewing the client’s insulin injection technique.`,
      `Obtaining the fingerstick blood glucose level before each meal and at bedtime.`,
      `Reminding the client to dry the toes carefully after a shower.`,
      `Talking to the client about foods that raise the blood glucose level.`,
    ],
    //optionFeedback: [``],
    optionStyleType: `st-decimal`,
    answer: [0, 2, 3],
    ansText: `<strong>Rationale:</strong> <p><strong>Contacting the dietitian for a prescribed consult.</strong> The UAP can perform clerical duties.</p>
<p><strong>Reviewing the client’s insulin injection technique.</strong> The RN is responsible for medication review and administration.</p>
<p><strong>Obtaining the fingerstick blood glucose level before each meal and at bedtime.</strong> The UAP can collect and report data such as vital signs, height and weight, and capillary blood sugar results.</p>
<p><strong>Reminding the client to dry their toes carefully after a shower.</strong> The UAP can perform hygiene tasks and reinforce teaching.</p>
<p><strong>Talking to the client about foods that raise the blood glucose level.</strong> Clients who need education or reinforcement of education require intervention by the RN.</p>`,
    state: `notAnswered`,
    userAnswered: [],
    type: `MCSM`,
  },
  {
    q: `The home health RN evaluates the insulin preparation and administration technique of a 36-year-old male client newly diagnosed with diabetes. The client has been prescribed lispro insulin before meals and glargine insulin once daily in the morning. Which finding indicates that the client needs further education?`,
    q2: ``,
    q3: [],
    quesHeading: `<span class="h1hd">8 Leadership and Delegation: </span>`,
    option: [
      `He mixes glargine and lispro in the same syringe for the morning dose.`,
      `He leaves the insulin syringe in place for 10 seconds after injection.`,
      `He stores the opened insulin vials at room temperature in the cabinet.`,
      `He recaps and disposes of the single-use insulin syringe.`,
    ],
    optionFeedback: [
      `Glargine and lispro must not be mixed with any other insulin.`,
      `This ensures that all of the insulin is absorbed.`,
      `Insulin is stored at room temperature, out of direct sunlight.`,
      `Clients may recap needles, but health care workers may not to reduce the risk of needlestick injury.`,
    ],
    optionStyleType: `st-decimal`,
    answer: [0],
    ansText: `<strong>Rationale:</strong> Glargine and lispro must not be mixed with any other insulin.`,
    state: `notAnswered`,
    userAnswered: [],
    type: `MCSS`,
  },
  {
    q: `At change of shift, the charge nurse assigns the UAP four clients. The charge nurse would direct the UAP to take vital signs on which client first?`,
    q2: ``,
    q3: [],
    quesHeading: `<span class="h1hd">8 Leadership and Delegation: </span>`,
    option: [
      `The 89-year-old with chronic obstructive pulmonary disease who is resting quietly on 2 L of oxygen and who needs assistance with a bath.`,
      `The client who returned from surgery and needs their second set of every-15-minute vital signs taken.`,
      `The client newly diagnosed with type 2 diabetes who had a fingerstick glucose level of 90 mg/dL (5 mmol/L) (Ref. range: 74–106 mg/dL or 4.1–5.9  mmol/L) and needs help with breakfast.`,
      `The newly admitted client with rheumatoid arthritis who needs hand splints reapplied to both hands.`,
    ],
    optionFeedback: [
      `This client is stable.`,
      `This client has a set of time-sensitive vital signs, so this is a priority.`,
      `This client is stable.`,
      `This client is stable.`,
    ],
    optionStyleType: `st-decimal`,
    answer: [1],
    ansText: `<strong>Rationale:</strong> This client has a set of time-sensitive vital signs, so this is a priority.`,
    state: `notAnswered`,
    userAnswered: [],
    type: `MCSS`,
  },
  {
    q: `The arrhythmia alarm sounds on a client on the telemetry unit, indicating that the client is in ventricular tachycardia. Place the RN’s actions for this client in order of priority from first to last.
    <ul class="numbers">
          <li><strong>Call the rapid response team.</strong></li>
          <li><strong>Assess for a pulse and blood pressure.</strong></li>
          <li><strong>Give oxygen via nasal cannula.</strong></li>
          <li><strong>Bring defibrillator/crash car to the bedside.</strong></li>
          <li><strong>Document the incident.</strong></li>
         </ul>`,
    q2: ``,
    q3: [],
    quesHeading: `<span class="h1hd">8 Leadership and Delegation: </span>`,
    option: [
      `1, 2, 3, 5, 4`,
      `3, 2, 1, 4, 5`,
      `5, 4, 3, 2, 1`,
      `2, 1, 3, 4, 5`,
      `1, 3, 2, 5, 4`,
    ],
    //optionFeedback: [``],
    optionStyleType: `st-decimal`,
    answer: [3],
    ansText: `<strong>Rationale:</strong> The RN needs to first assess the client before calling the rapid response team. Also, if the client is truly in ventricular tachycardia, it needs to be determined if it is pulseless v-tach or if the client has a pulse and blood pressure. If there is a pulse, the second action would be to call the rapid response team so that additional help is available. Then, the client needs to have oxygen to maximize oxygenation of the circulating blood. The defibrillator needs to be brought to the bedside to be used for cardioversion. The final activity is to document the findings.`,
    state: `notAnswered`,
    userAnswered: [],
    type: `MCSS`,
  },
  {
    q: `The RN is reviewing the laboratory values for their assigned clients. Which client has an abnormal laboratory report that the RN would immediately call to the HCP?`,
    q2: ``,
    q3: [],
    quesHeading: `<span class="h1hd">8 Leadership and Delegation: </span>`,
    option: [
      `The female client who is postsplenectomy after a motor vehicle accident and has a hemoglobin of 10.9 g/dL (6.2 mmol/L) (Ref. range: 14–18 g/dL or 8.7–11.2 mmol/L).`,
      `The client receiving warfarin (Coumadin) who has an international normalized ratio (INR) of 2.3 (Ref. range: 0.8–1.1).`,
      `The 38-year-old client who is 24 hours post thyroidectomy and has a total calcium level of 9.4 mg/dL (2.3 mmol/L) (Ref. range: 9–10 mg/dL or 2.25 mmol/L–2.75 mmol/L).`,
      `The newly admitted client with bipolar disorder with a lithium level of 2.5 mEq/L (2.5 mmol/L) (Ref. range: 0.8–1.2 mEq/L or 0.8–1.2 mmol/L).`,
    ],
    optionFeedback: [
      `This hemoglobin level is low but not at a critical level. This is not the priority.`,
      `This lab value is therapeutic and expected.`,
      `This lab value is within normal limits.`,
      `Severe lithium toxicity occurs at 2.0 mEq/L; the RN should notify the HCP immediately.`,
    ],
    optionStyleType: `st-decimal`,
    answer: [3],
    ansText: `<strong>Rationale:</strong> Severe lithium toxicity occurs at 2.0 mEq/L; the RN should notify the HCP immediately.`,
    state: `notAnswered`,
    userAnswered: [],
    type: `MCSS`,
  },
  {
    q: `The RN receives a change-of-shift report on their four acute care clients. Which action would the RN take first?`,
    q2: ``,
    q3: [],
    quesHeading: `<span class="h1hd">8 Leadership and Delegation: </span>`,
    option: [
      `Administer an antiemetic to a postoperative client who has been nauseated and is now vomiting.`,
      `Notify a family member of a client’s impending transfer to the intensive care unit for angina and ST-segment changes.`,
      `Inform the HCP of a potassium level of 5.2 mEq/L (5.2 mmol/L) (Ref. range: 3.5–5 mEq/L or 3.5–5 mmol/L) in the client with end-stage renal disease.`,
      `Begin assessment rounds, starting with the palliative care client having a diagnosis of congestive failure.`,
    ],
    optionFeedback: [
      `Postoperative nausea and vomiting (PONV) are among the most common reactions after surgery. PONV can stress and irritate abdominal and GI wounds, increase intracranial pressure in clients who had head and neck surgery, elevate intraocular pressure in clients who had eye surgery, and increase the risk for aspiration. Administering an antiemetic for relieving PONV will decrease these risks.`,
      `This is a change in status and should be performed after managing the PONV.`,
      `This is an expected finding in end-stage renal disease.`,
      `Assessing the client receiving palliative care is important; however, managing the client with PONV is the priority.`,
    ],
    optionStyleType: `st-decimal`,
    answer: [0],
    ansText: `<strong>Rationale:</strong> Postoperative nausea and vomiting (PONV) are among the most common reactions after surgery. PONV can stress and irritate abdominal and GI wounds, increase intracranial pressure in clients who had head and neck surgery, elevate intraocular pressure in clients who had eye surgery, and increase the risk for aspiration. Administering an antiemetic for relieving PONV will decrease these risks.`,
    state: `notAnswered`,
    userAnswered: [],
    type: `MCSS`,
  },
  {
    q: `The emergency department staff RN is assigned four clients. Which client would the RN assess first?`,
    q2: ``,
    q3: [],
    quesHeading: `<span class="h1hd">8 Leadership and Delegation: </span>`,
    option: [
      `A preschooler with a barking cough, an O<sub>2</sub> saturation of 93% on room air, and occasional inspiratory stridor.`,
      `A 10-month-old infant with a tympanic temperature of 102°F (38.9°C) and green nasal drainage who is pulling at her ears.`,
      `A crying 8-month-old with a harsh, paroxysmal cough; an audible expiratory wheeze; and mild retractions.`,
      `A clingy 3-year-old who has a sore throat and drooling and whose tongue is slightly protruding from his mouth.`,
    ],
    optionFeedback: [
      `This is not a medical emergency. With an O<sub>2</sub> saturation of 93%, the child is not in acute respiratory distress.`,
      `The child has an infection and probably needs antibiotics, but this is not a medical emergency.`,
      `These symptoms are often seen with children with croup. While the child does need humidified air, they are not in acute respiratory distress.`,
      `Drooling, a history of sore throat, and a protruding tongue are classic manifestations of epiglottitis; this is a medical emergency. The throat can quickly occlude and cause respiratory arrest.`,
    ],
    optionStyleType: `st-decimal`,
    answer: [3],
    ansText: `<strong>Rationale:</strong> Drooling, a history of sore throat, and a protruding tongue are classic manifestations of epiglottitis; this is a medical emergency. The throat can quickly occlude and cause respiratory arrest.`,
    state: `notAnswered`,
    userAnswered: [],
    type: `MCSS`,
  },
  {
    q: `The outpatient clinic nurse is reviewing phone messages from the previous night. Which client would the RN call back first?`,
    q2: ``,
    q3: [],
    quesHeading: `<span class="h1hd">8 Leadership and Delegation: </span>`,
    option: [
      `A woman at 30 weeks’ gestation who has been diagnosed with mild preeclampsia and was unable to relieve her heartburn.`,
      `A woman at 24 weeks’ gestation who was crying about painful vulvar lesions and urinary frequency for the past 8 hours.`,
      `A woman at 12 weeks’ gestation who was recently discharged from the hospital with hyperemesis gravidarum and has had two episodes of vomiting in 6 hours.`,
      `A woman with type 1 diabetes who tested positive with a home pregnancy kit and was worried about managing her diabetes.`,
    ],
    optionFeedback: [
      `A sign of a potential complication of eclampsia is epigastric pain, which may be indicative of liver damage and HELLP (hemolysis, elevated liver enzymes, low platelet count) syndrome, a medical emergency.`,
      `These are concerns, possibly indications of a sexually transmitted disease. But these concerns do not take priority over the client with possible HELLP syndrome.`,
      `This client does need to be followed up with for possible dehydration, but the client with possible HELLP syndrome takes precedence.`,
      `This client needs education, but this is not a priority.`,
    ],
    optionStyleType: `st-decimal`,
    answer: [0],
    ansText: `<strong>Rationale:</strong> A sign of a potential complication of eclampsia is epigastric pain, which may be indicative of liver damage and HELLP (hemolysis, elevated liver enzymes, low platelet count) syndrome, a medical emergency.`,
    state: `notAnswered`,
    userAnswered: [],
    type: `MCSS`,
  },
  {
    q: `The clinic nurse suspects that a 2-year-old child is being abused. Which assessment finding(s) would support this?`,
    q2: ``,
    q3: [],
    quesHeading: `<span class="h1hd">8 Leadership and Delegation: </span>`,
    option: [
      `Petechiae in a straight line on the chest.`,
      `Gray-blue pigmented areas on the sacral region.`,
      `Bald patches on the scalp.`,
      `Ear tugging and crying.`,
      `Symmetrical burns on the hands.`,
    ],
    //optionFeedback: [``],
    optionStyleType: `st-decimal`,
    answer: [2, 4],
    ansText: `<strong>Rationale:</strong> <p><strong>Petechiae in a straight line on the chest.</strong> Petechiae on the chest may be the result of the coining procedure, a cultural practice among Southeast Asian populations.</p>
<p><strong>Gray-blue pigmented areas on the sacral region.</strong> These are Mongolian spots, blue areas commonly located on the sacral region that are consistent in shape and color.</p>
<p><strong>Bald patches on the scalp.</strong> Bald patches typically are symmetrical and are indicative of physical abuse.</p>
<p><strong>Ear tugging and crying.</strong> Ear tugging and crying are typical signs of otitis media.</p>
<p><strong>Symmetrical burns on the hands.</strong> Symmetrical burns are indicative of physical abuse.</p>`,
    state: `notAnswered`,
    userAnswered: [],
    type: `MCMS`,
  },
  {
    q: `The RN is caring for a client who had a thoracotomy 48 hours earlier and now has left lower lobe chest tubes. The RN notes that a chest tube is not tidaling. Which action would the RN take first?`,
    q2: ``,
    q3: [],
    quesHeading: `<span class="h1hd">8 Leadership and Delegation: </span>`,
    option: [
      `Check for kinks in the chest drainage system.`,
      `Assess the heart rate and blood pressure.`,
      `Notify the rapid response team immediately.`,
      `Reconnect the chest tube to wall suction.`,
    ],
    optionFeedback: [
      `Normal fluctuation of the water, called tidaling, reflects the intrapleural pressure during inspiration and expiration. If no tidaling is observed (rising with inspiration and falling with expiration in a spontaneously breathing client), the drainage system may be blocked. An absence of fluctuation may mean that the lung has fully healed (which is unlikely at 48 hours), or it can mean that there is an obstruction in the chest tube. A simple step is to ensure that there are no kinks that would occlude the chest tube and prevent lung drainage and expansion.`,
      `Checking the heart rate and blood pressure is not directly related to the lack of chest tube drainage.`,
      `Although the RN should immediately notify the rapid response team for tracheal deviation, sudden onset of dyspnea, or mediastinal shift, the absence of tidaling may not be a medical emergency.`,
      `When a chest tube is connected to wall suction, tidaling may stop. The RN should disconnect the tube, not reconnect it, to observe for tidaling.`,
    ],
    optionStyleType: `st-decimal`,
    answer: [0],
    ansText: `<strong>Rationale:</strong> Normal fluctuation of the water, called tidaling, reflects the intrapleural pressure during inspiration and expiration. If no tidaling is observed (rising with inspiration and falling with expiration in a spontaneously breathing client), the drainage system may be blocked. An absence of fluctuation may mean that the lung has fully healed (which is unlikely at 48 hours), or it can mean that there is an obstruction in the chest tube. A simple step is to ensure that there are no kinks that would occlude the chest tube and prevent lung drainage and expansion.`,
    state: `notAnswered`,
    userAnswered: [],
    type: `MCSS`,
  },
  {
    q: `While the RN is caring for a client who has had a myocardial infarction, the monitor alarm sounds, and the RN notes ventricular fibrillation. Which is the RN’s first course of action?`,
    q2: ``,
    q3: [],
    quesHeading: `<span class="h1hd">8 Leadership and Delegation: </span>`,
    option: [
      `Notify the HCP.`,
      `Increase the oxygen concentration.`,
      `Assess the client.`,
      `Prepare to defibrillate the client.`,
    ],
    optionFeedback: [
      `This may be an appropriate action after assessment of the client’s clinical status.`,
      `This may be an appropriate action after assessment of the client’s clinical status.`,
      `If a monitor alarm sounds, the RN should first assess the client’s clinical status to see whether the problem is an actual dysrhythmia or a monitoring system malfunction.`,
      `This may be an appropriate action after assessment of the client’s clinical status.`,
    ],
    optionStyleType: `st-decimal`,
    answer: [2],
    ansText: `<strong>Rationale:</strong> If a monitor alarm sounds, the RN should first assess the client’s clinical status to see whether the problem is an actual dysrhythmia or a monitoring system malfunction.`,
    state: `notAnswered`,
    userAnswered: [],
    type: `MCSS`,
  },
  {
    q: `The HCP has prescribed the removal of a client’s internal jugular central line catheter. To remove the catheter safely, the RN would give which intervention(s) the highest priority?`,
    q2: ``,
    q3: [],
    quesHeading: `<span class="h1hd">8 Leadership and Delegation: </span>`,
    option: [
      `Carefully remove the bio-occlusive dressing.`,
      `Place the client in the Trendelenburg position.`,
      `Send the catheter tip to the laboratory for a culture and sensitivity.`,
      `Have the client hold a deep breath during removal.`,
      `Apply pressure for 20 minutes after removal of the catheter.`,
    ],
    //optionFeedback: [``],
    optionStyleType: `st-decimal`,
    answer: [1, 3],
    ansText: `<strong>Rationale:</strong> <p><strong>Carefully remove the bio-occlusive dressing.</strong> Removing the bio-occlusive dressing is important, but it is not a safety priority.</p>
<p><strong>Place the client in the Trendelenburg position.</strong> The procedure for removing the catheter safely is (1) place the client in the Trendelenburg position, (2) have the client take a deep breath and hold it, and (3) gently withdraw the catheter while applying direct pressure with sterile gauze. Holding the breath creates positive pressure in the intrathoracic space, and the Trendelenburg position minimizes the risk of air entering the catheter.</p>
<p><strong>Send the catheter tip to the lab for culture and sensitivity.</strong> The catheter tip may or may not be sent to the lab, depending on the protocol of the facility.</p>
<p><strong>Have the client hold a deep breath during removal.</strong> See the explanation for 2.</p>
<p><strong>Apply pressure for 20 minutes after removal of the catheter.</strong> Applying pressure for 20 minutes is a technique used in arterial line withdrawal to prevent bleeding.</p>`,
    state: `notAnswered`,
    userAnswered: [],
    type: `MCMS`,
  },
  {
    q: `The RN who usually works on the orthopedic surgery unit is floating to a cardiovascular unit. Which client would be best to assign to the float RN?`,
    q2: ``,
    q3: [],
    quesHeading: `<span class="h1hd">8 Leadership and Delegation: </span>`,
    option: [
      `Client scheduled for a heart catheterization this morning.`,
      `Client admitted last night for chest pain.`,
      `Client who is 1 day postoperative for popliteal bypass surgery.`,
      `Client with heart failure and scheduled for a stress test today.`,
    ],
    optionFeedback: [
      `Preparing the client for a cardiac catheterization requires specialized information, and it would be best to assign this client to the RN who usually works on the cardiovascular unit.`,
      `This client requires close monitoring by the RN who has additional education about cardiac issues.`,
      `This would require similar care to a client who had just had lower extremity orthopedic surgery and would be the safest assignment for this RN.`,
      `Preparing the client for a stress test requires specialized information and would be best to assign to the RN who usually works on the cardiovascular unit.`,
    ],
    optionStyleType: `st-decimal`,
    answer: [2],
    ansText: `<strong>Rationale:</strong> This would require similar care to a client who had just had lower extremity orthopedic surgery and would be the safest assignment for this RN.`,
    state: `notAnswered`,
    userAnswered: [],
    type: `MCSS`,
  },
  {
    q: `The RN is admitting a client who is a paraplegic and has a nonhealing pressure injury with a possible methicillin-resistant Staphylococcus aureus (MRSA) infection. A practical nurse (PN) and UAP are assigned to the RN’s team. Which task(s) would be delegated to the PN?`,
    q2: ``,
    q3: [],
    quesHeading: `<span class="h1hd">8 Leadership and Delegation: </span>`,
    option: [
      `Place the client in isolation.`,
      `Complete a dressing change.`,
      `Assess and document the wound.`,
      `Insert a urinary catheter.`,
      `Administer oral pain medications.`,
    ],
    //optionFeedback: [``],
    optionStyleType: `st-decimal`,
    answer: [1, 3, 4],
    ansText: `<strong>Rationale:</strong> <p><strong>Place the client in isolation.</strong> This task can be safely assigned to the UAP.</p>
<p><strong>Complete a dressing change.</strong> This task is within the scope of practice for the PN.</p>
<p><strong>Assess and document the wound.</strong> Initial assessment of a wound should be completed by the RN.</p>
<p><strong>Insert a urinary catheter.</strong> This task is within the scope of practice for the PN.</p>
<p><strong>Administer oral pain medications.</strong> This task is within the scope of practice for the PN.</p>`,
    state: `notAnswered`,
    userAnswered: [],
    type: `MCMS`,
  },
  {
    q: `Which client would the RN anticipate receiving as a transfer to the medical-surgical unit from the step-down unit?`,
    q2: ``,
    q3: [],
    quesHeading: `<span class="h1hd">8 Leadership and Delegation: </span>`,
    option: [
      `A client admitted for an ST-elevation myocardial infarction (STEMI) who just returned from having a cardiac catheterization performed.`,
      `A client diagnosed with congestive heart failure who is receiving an IV infusion of furosemide.`,
      `A client with possible Guillain-Barré syndrome who may need an exchange transfusion.`,
      `A client in hypertensive crisis who is prescribed a sodium nitroprusside drip.`,
    ],
    optionFeedback: [
      `This client needs close monitoring for the first 24 hours and should remain on the step-down unit.`,
      `This client could be safely taken care of on a medical-surgical unit.`,
      `This client needs close monitoring and should remain in the step-down unit.`,
      `Clients on a nitroprusside drip need frequent vital signs and close monitoring. This client should remain on the step-down unit.`,
    ],
    optionStyleType: `st-decimal`,
    answer: [1],
    ansText: `<strong>Rationale:</strong> This client could be safely taken care of on a medical-surgical unit.`,
    state: `notAnswered`,
    userAnswered: [],
    type: `MCSS`,
  },
  {
    q: `When accessing the medication-dispensing system (Pyxis), the RN finds chlorpropamide in the drawer instead of the expected chlorpromazine. Which action(s) would the RN take?`,
    q2: ``,
    q3: [],
    quesHeading: `<span class="h1hd">8 Leadership and Delegation: </span>`,
    option: [
      `Remove the tablets of chlorpropamide.`,
      `Notify the pharmacy about the mistake.`,
      `Complete an incident occurrence report.`,
      `Be extra vigilant because pharmacy is making mistakes.`,
      `Place a warning note on the Pyxis machine.`,
    ],
    //optionFeedback: [``],
    optionStyleType: `st-decimal`,
    answer: [0, 1, 2],
    ansText: `<strong>Rationale:</strong> <p><strong>Remove the tablets of chlorpropamide.</strong> The RN needs to ensure that others do not administer the wrong medication, so the tablets of chlorpropamide need to be removed and returned to the pharmacy.</p>
<p><strong>Notify the pharmacy about the mistake.</strong> The pharmacy needs to be made aware of the error.</p>
<p><strong>Complete an incident or occurrence report.</strong> An incident (also called an occurrence) report completed to help prevent the error in the future.</p>
<p><strong>Be extra vigilant because the pharmacy is making mistakes.</strong> This action is not needed, as this may be a one-time occurrence.</p>
<p><strong>Place a warning note on the Pyxis machine.</strong> This action is not needed.</p>`,
    state: `notAnswered`,
    userAnswered: [],
    type: `MCMS`,
  },
  {
    q: `The RN is calling the HCP about a client’s current needs. Which is the best way to communicate?`,
    q2: ``,
    q3: [],
    quesHeading: `<span class="h1hd">8 Leadership and Delegation: </span>`,
    option: [
      `Call the HCP with the request and a recommendation.`,
      `Use the SBAR (situation, background, assessment, recommendation) tool for communication.`,
      `Send a text message or page with the needed order.`,
      `Ask the HCP to come back to the unit to discuss the client’s needs.`,
    ],
    optionFeedback: [
      `Letting the physician know the needs of the client is important, but key information may be missed using this way to communicate.`,
      `Using the SBAR format ensures that all key information is given and is the best way to communicate.`,
      `This may be an ineffective way to communicate and may not ensure that all key information is given. Additionally, if both phones are not encrypted, this may place the client’s information at risk.`,
      `Although face-to-face communication is often valuable, this does not ensure that all key information is communicated.`,
    ],
    optionStyleType: `st-decimal`,
    answer: [1],
    ansText: `<strong>Rationale:</strong> Using the SBAR format ensures that all key information is given and is the best way to communicate.`,
    state: `notAnswered`,
    userAnswered: [],
    type: `MCSS`,
  },
  {
    q: `The HCP plans to do a paracentesis on a client with cirrhosis in 1 hour. In which order would the RN perform the following activities?
        <ul class="numbers">
          <li><strong>Ensure that the informed consent has been obtained.</strong></li>
          <li><strong>Measure the client’s abdominal girth.</strong></li>
          <li><strong>Have the client empty his or her bladder.</strong></li>
          <li><strong>Assemble needed equipment.</strong></li>
          <li><strong>Administer oral pain medication.</strong></li>
         </ul>`,
    q2: ``,
    q3: [],
    quesHeading: `<span class="h1hd">8 Leadership and Delegation: </span>`,
    option: [
      `1, 2, 3, 5, 4`,
      `3, 2, 1, 4, 5`,
      `1, 5, 3, 2, 4`,
      `2, 1, 3, 4, 5`,
      `1, 3, 2, 5, 4`,
    ],
    //optionFeedback: [``],
    optionStyleType: `st-decimal`,
    answer: [2],
    ansText: `<p>
    <strong>Rationale:</strong> <strong>Correct order: 1, 5, 3, 2, 4. </strong> Before a procedure can be completed, it is essential to have an informed consent (1). Oral pain medication can then be given (after the consent has been obtained) to help the client relax during the procedure (5). The client then needs to empty his or her bladder before the procedure to prevent accidentally puncturing the bladder (3). After the bladder is empty, a baseline abdominal girth is obtained (2). Finally, the RN needs to assemble the correct equipment for the procedure (4).</p>`,
    state: `notAnswered`,
    userAnswered: [],
    type: `MCSS`,
  },
  {
    q: `The RN receives report on a client from the emergency department with a diagnosis of pneumonia. Which intervention has the highest priority?`,
    q2: ``,
    q3: [],
    quesHeading: `<span class="h1hd">8 Leadership and Delegation: </span>`,
    option: [
      `Obtain blood cultures.`,
      `Initiate prescribed antibiotics.`,
      `Place the client in isolation.`,
      `Obtain an accurate weight.`,
    ],
    optionFeedback: [
      `Blood cultures are not needed unless the client is suspected of being septic.`,
      `Studies have shown that the sooner antibiotics are started, the better the outcomes. Current requirements include antibiotic administration within 2 hours of diagnosis. This is the priority.`,
      `The question does not state which organism is causing the pneumonia, so this may not be needed.`,
      `This would be needed if the antibiotic is weight based but is not usually a priority.`,
    ],
    optionStyleType: `st-decimal`,
    answer: [1],
    ansText: `<strong>Rationale:</strong> Studies have shown that the sooner antibiotics are started, the better the outcomes. Current requirements include antibiotic administration within 2 hours of diagnosis. This is the priority.`,
    state: `notAnswered`,
    userAnswered: [],
    type: `MCSS`,
  },
  {
    q: `The RN is part of the triage team at a disaster. Which client would be treated first?`,
    q2: ``,
    q3: [],
    quesHeading: `<span class="h1hd">8 Leadership and Delegation: </span>`,
    option: [
      `A 90-year-old woman with a crushed pelvis and head injuries.`,
      `A 21-year-old man screaming in pain from a broken leg.`,
      `A 30-year-old woman with a flail chest secondary to a puncture wound to the chest.`,
      `A 12-year-old crying with multiple lacerations to both legs.`,
    ],
    optionFeedback: [
      `This client would be triaged black.`,
      `This client’s injuries are not life-threatening, and he can wait to be seen.`,
      `The flail chest causes the heart to become unstable and is life-threatening. This client needs to be seen immediately.`,
      `Although the child needs to be comforted, the injuries are not life-threatening, and this client can wait for treatment.`,
    ],
    optionStyleType: `st-decimal`,
    answer: [2],
    ansText: `<strong>Rationale:</strong> The flail chest causes the heart to become unstable and is life-threatening. This client needs to be seen immediately.`,
    state: `notAnswered`,
    userAnswered: [],
    type: `MCSS`,
  },
  {
    q: `The triage RN in the emergency room is assessing four clients. Which client requires the most immediate intervention?`,
    q2: ``,
    q3: [],
    quesHeading: `<span class="h1hd">8 Leadership and Delegation: </span>`,
    option: [
      `The adult client who arrived via ambulance with numbness and tingling of his left arm and face.`,
      `The adult client who had a seizure at home who is sleeping on his left side.`,
      `The 60-year-old client who complains of frequent urination and has a blood sugar of 300 mg/dL (16.7 mmol/L) (Ref. range: 74–106 mg/dL or 4.1–5.9 mmol/L).`,
      `The middle-aged client who presents with severe unilateral back pain and previous history of kidney stones.`,
    ],
    optionFeedback: [
      `The client may be experiencing a stroke and requires immediate assessment and interventions. If interventions are initiated quickly, the complications may be reversed.`,
      `While a seizure is highly concerning, the priority is the client who may be diagnosed with a stroke.`,
      `An elevated blood sugar may indicate diabetes, and polyuria is an expected symptom. It is considered urgent and not emergent.`,
      `Although this is highly concerning, the client exhibiting symptoms of a stroke is a higher priority.`,
    ],
    optionStyleType: `st-decimal`,
    answer: [0],
    ansText: `<strong>Rationale:</strong> The client may be experiencing a stroke and requires immediate assessment and interventions. If interventions are initiated quickly, the complications may be reversed.`,
    state: `notAnswered`,
    userAnswered: [],
    type: `MCSS`,
  },
  {
    q: `After the change-of-shift report on an orthopedic floor, which client would the RN assess first?`,
    q2: ``,
    q3: [],
    quesHeading: `<span class="h1hd">8 Leadership and Delegation: </span>`,
    option: [
      `A client who had surgery yesterday and has a temperature of 99.7°F (37.6°C).`,
      `A client who is complaining of numbness and tingling distal to the fracture site.`,
      `A client who had a left leg amputation and states he is experiencing pain in the left foot.`,
      `A client who is extremely upset with their care and is requesting to speak to the manager.`,
    ],
    optionFeedback: [
      `A slight increase in temperature is expected postoperatively.`,
      `This is a sign of compartment syndrome. This client needs to be assessed first.`,
      `Phantom pain is expected after an amputation and should be treated but is not as critical as assessing for compartment syndrome.`,
      `This is a customer service issue and needs to be addressed but is not the highest priority.`,
    ],
    optionStyleType: `st-decimal`,
    answer: [1],
    ansText: `<strong>Rationale:</strong> This is a sign of compartment syndrome. This client needs to be assessed first.`,
    state: `notAnswered`,
    userAnswered: [],
    type: `MCSS`,
  },
  {
    q: `The RN is administering medications to a client admitted for an overdose and a history of substance abuse. Which intervention(s) is/are a priority to include in this client’s plan of care?`,
    q2: ``,
    q3: [],
    quesHeading: `<span class="h1hd">8 Leadership and Delegation: </span>`,
    option: [
      `Allow the client to take medications independently.`,
      `Ensure that all medications have been swallowed before leaving the client’s room.`,
      `Request that oral pain medications be changed from tablet to oral suspension.`,
      `Administer flumazenil as prescribed every 6 hours around the clock.`,
      `Administer all medications to the client via the intravenous route.`,
    ],
    //optionFeedback: [``],
    optionStyleType: `st-decimal`,
    answer: [1, 2],
    ansText: `<strong>Rationale:</strong> <p><strong>Allow the client to take medications indepen-dently.</strong> With a history of substance abuse, the RN needs to observe the client as medications are taken.</p>
<p><strong>Ensure that all medications have been swallowed before leaving the client’s room.
</strong> To ensure that medications are not being hoarded or kept to be taken at a later time, the RN needs to watch the client swallow his or her medications.</p>
<p><strong>Request that oral pain medications be changed from tablet to oral suspension.</strong> Liquid forms of medications are harder to save to be taken later so are often used for clients with a history of substance abuse.</p>
<p><strong>Administer flumazenil as prescribed every 6 hours around the clock.</strong> Flumazenil is used to reverse benzodiazepine overdose and is given as needed, not around the clock.
</p>
<p><strong>Administer all medications to the client via the intravenous route.</strong> There is no indication to give medications intravenously.
</p>`,
    state: `notAnswered`,
    userAnswered: [],
    type: `MCMS`,
  },
  {
    q: `The RN is returning phone calls to clients who are cared for at an outpatient mental health center. Which client would the RN call first?`,
    q2: ``,
    q3: [],
    quesHeading: `<span class="h1hd">8 Leadership and Delegation: </span>`,
    option: [
      `The young mother diagnosed with schizophrenia who is hearing voices saying that they are pursuing her children.`,
      `The elderly man at an assisted living facility who says he wants to end it all.`,
      `The female client diagnosed with bipolar disorder who has not slept for 48 hours.`,
      `The teenager diagnosed with bulimia whose mother called and reported that she found her daughter purging.`,
    ],
    optionFeedback: [
      `This client is at risk for hurting herself or her children. She needs to be seen first.`,
      `This client is at risk for committing suicide, but he lives in a facility where there is staff that the RN can notify about his thoughts. The staff can stay with him until he can be brought into the clinic.`,
      `Although this client needs to be seen to have her medications adjusted, she is not the priority client.`,
      `This client does need to be seen but is not in imminent danger.`,
    ],
    optionStyleType: `st-decimal`,
    answer: [0],
    ansText: `<strong>Rationale:</strong> This client is at risk for hurting herself or her children. She needs to be seen first.`,
    state: `notAnswered`,
    userAnswered: [],
    type: `MCSS`,
  },
  {
    q: `An 18-year-old woman is being discharged after delivering a healthy baby. She has a cousin whose baby died from sudden infant death syndrome (SIDS). The client seems to know many of the precautions to take. Which information does the RN need to correct?`,
    q2: ``,
    q3: [],
    quesHeading: `<span class="h1hd">8 Leadership and Delegation: </span>`,
    option: [
      `Always place infants on their backs to sleep.`,
      `Room sharing has been shown to decrease SIDS.`,
      `Keep the crib free of stuffed animals and crib pads.`,
      `Sleeping with the baby can alert the mother to changes.`,
    ],
    optionFeedback: [
      `This is correct. Babies should be placed on their backs.`,
      `This is correct. Studies show that room sharing does decrease SIDS.`,
      `This is correct. The bed should be free of items that could cause suffocation.`,
      `Sleeping with the baby increases the risk for injury and SIDS for infants.`,
    ],
    optionStyleType: `st-decimal`,
    answer: [3],
    ansText: `<strong>Rationale:</strong> Sleeping with the baby increases the risk for injury and SIDS for infants.`,
    state: `notAnswered`,
    userAnswered: [],
    type: `MCSS`,
  },
  {
    q: `A 4-year-old admitted with pneumonia weighs 39.6 pounds (18 kg). The HCP has prescribed vancomycin 40 mg/kg/day IV. The order states to divide the dose and give it three times daily. How many milligrams of vancomycin would the child receive in each dose? (Round the answer to the nearest whole number.)`,
    q2: ``,
    q3: [],
    quesHeading: `<span class="h1hd">8 Leadership and Delegation: </span>`,
    option: [
      "180 mg",
      "240 mg",
      "360 mg",
      "300 mg",
    ],
    optionStyleType: `st-decimal`,
    answer: [1],
    ansText: `<p><strong>Rationale:</strong></p><div style="text-align:center;"><math xmlns="http://www.w3.org/1998/Math/MathML"><mrow><mfrac><mrow><mn>40</mn><mo>&#xA0;</mo><mi>m</mi><mi>g</mi><mo>×</mo><mn>18</mn><mo>&#xA0;</mo><mi>k</mi><mi>g</mi></mrow><mrow><mn>3</mn><mo>&#xA0;</mo><mi>d</mi><mi>o</mi><mi>s</mi><mi>e</mi><mi>s</mi></mrow></mfrac><mo>=</mo><mn>240</mn><mo>&#xA0;</mo><mi>m</mi><mi>g</mi><mo>/</mo><mi>dose</mi></mrow></math></div>`,
    state: `notAnswered`,
    userAnswered: [],
    type: `MCSS`,
  },
  {
    q: `The RN needs to initiate an IV on an 8-year-old child. Which intervention(s) is/are appropriate? (Select all that apply).`,
    q2: ``,
    q3: [],
    quesHeading: `<span class="h1hd">8 Leadership and Delegation: </span>`,
    option: [
      `Start the IV in the treatment room, not the child’s room.`,
      `Apply a lidocaine-based cream for a few minutes before starting the IV.`,
      `Ask the parents to leave the room while performing the procedure.`,
      `Encourage the child to use guided imagery to cope.`,
      `Offer the child a reward if they cooperate during the procedure.`,
    ],
    //optionFeedback: [``],
    optionStyleType: `st-decimal`,
    answer: [0, 3],
    ansText: `<strong>Rationale:</strong> <p><strong>Start the IV in the treatment room, not the child’s room.</strong> The child’s room is a safe zone, and painful treatments should not be performed in the child’s room.</p>
<p><strong>Apply a lidocaine-based cream for a few minutes before starting the IV.</strong> To be effective, the cream needs to be applied for about 1 hour before the IV is started.</p>
<p><strong>Ask the parents to leave the room while performing the procedure.</strong> Having parents present can help the child cope with this procedure.</p>
<p><strong>Encourage the child to use guided imagery to cope.</strong> hildren at this age can understand and participate in guided imagery.</p>
<p><strong>Offer the child a reward if they cooperate during the procedure.</strong> Offering the child a reward does not help the child to cope with the IV insertion.</p>`,
    state: `notAnswered`,
    userAnswered: [],
    type: `MCMS`,
  },
];
